/* Generated code. Do not edit. */
type GalaxyTuple = [number, string];
const inputGalaxies: GalaxyTuple[] = [
    [0, "Euclid"],
    [1, "Hilbert Dimension"],
    [2, "Calypso"],
    [3, "Hesperius Dimension"],
    [4, "Hyades"],
    [5, "Ickjamatew"],
    [6, "Budullangr"],
    [7, "Kikolgallr"],
    [8, "Eltiensleen"],
    [9, "Eissentam"],
    [10, "Elkupalos"],
    [11, "Aptarkaba"],
    [12, "Ontiniangp"],
    [13, "Odiwagiri"],
    [14, "Ogtialabi"],
    [15, "Muhacksonto"],
    [16, "Hitonskyer"],
    [17, "Rerasmutul"],
    [18, "Isdoraijung"],
    [19, "Doctinawyra"],
    [20, "Loychazinq"],
    [21, "Zukasizawa"],
    [22, "Ekwathore"],
    [23, "Yeberhahne"],
    [24, "Twerbetek"],
    [25, "Sivarates"],
    [29, "Sudzerbal"],
    [34, "Ijsenufryos"],
    [35, "Nipikulha"],
    [41, "Xobeurindj"],
    [254, "Iousongola"],
];
export { inputGalaxies, GalaxyTuple };
